name: pure_ui_kit_example
description: "Example app for Pure UI Kit"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pure_ui_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

assets:
  - assets/fonts/

fonts: 
  - family: inter
    fonts:
      - asset: assets/fonts/inter.ttf

flutter:
  uses-material-design: true